#! /bin/sh

xrandr --output eDP-1 --right-of HDMI-1 &
polybar example &
polybar example2 &
compton &
sxhkd &
xbindkeys &
feh --bg-scale Pictures/bg.jpg &

xset +fp /home/sebastian/.fonts &
xset fp rehash &



bspc monitor eDP-1 -d whatever 
bspc monitor HDMI-1 -d www communication editor media terminal random

bspc config border_width         1
bspc config window_gap         	 5 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='www'
bspc rule -a "Prospect Mail" desktop='communication'
bspc rule -a "microsoft teams - preview" desktop='communication'
bspc rule -a "code" desktop='editor'
bspc rule -a "spotify" desktop='media'
bspc rule -a "termite" desktop='terminal'
