#! /bin/sh

polybar example &
sxhkd &
konsole &
xbindkeys &

# feh --bg-scale Pictures/bg.jpg &

bspc monitor eDP-1 -d 1 2 3 4 5 6 
bspc monitor HDMI-1 -d 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
